[project]
name = "django-partvault"
version = "0.1.0"
description = "Part Vault - Yet another inventory management program"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.0.1",
    "django-bootstrap5>=26.1",
    "pillow>=12.1.0",
    "ruff>=0.15.0",
]
